name: test-dclane-hi 
base: core20 # the base snap is the execution environment for this snap
version: '1.0' # just for humans, typically '1.2+git' or '1.3.2'
summary: first snap on github
description: |
  nothing useful to say about hello world

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  dclane-hi:
    command: usr/local/bin/dclane_hi

parts:
  dclane-hi:
    # See 'snapcraft plugins'
    plugin: autotools
    #source: dclane-hi-1.0.tar.gz
    source: https://github.com/dclane-code/snaptest.git
